version: '3.7'

services:
  address-service:
    image: maradga/address-service-h2:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8181:8181"
    networks:
      - faculty-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411
  
  student-service:
    image: maradga/student-service-h2:0.0.1-SNAPSHOT
    mem_limit: 1000m
    ports:
      - "8080:8080"
    networks:
      - faculty-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411
   
  api-gateway:
    image: maradga/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - faculty-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411
          
  eureka-server:
    image: maradga/eureka-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - faculty-network
      
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - faculty-network
      
networks:
  faculty-network: