apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: student-service
  name: student-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
      - image: maradga/student-service-h2:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: student-service-h2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: student-service
  name: student-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: student-service
  sessionAffinity: None
  type: LoadBalancer

